name: ht_authentication_firebase
description: A starting point for Dart libraries or applications.
publish_to: none
repository: https://github.com/headlines-toolkit/ht-authentication-firebase

environment:
  sdk: ^3.7.2

dependencies:
  firebase_auth: ^3.4.0
  ht_authentication_client:
    git:
      url: https://github.com/headlines-toolkit/ht-authentication-client.git
      ref: main

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^7.0.0
