name: ht_authentication_firebase
description: Firebase implementation of the `ht_authentication_client` interface.
publish_to: none
repository: https://github.com/headlines-toolkit/ht-authentication-firebase

environment:
  sdk: ^3.7.0

dependencies:
  firebase_auth: ^5.5.2
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  ht_authentication_client:
    git:
      url: https://github.com/headlines-toolkit/ht-authentication-client.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
