name: ht_authentication_firebase

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request: 
    branches: 
      - main
  push: 
    branches: 
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: 3.7.2
      min_coverage: 75
      coverage_excludes: "*.g.dart"
